#!/usr/bin/env nbb
;; Snapshot a real Filecoin mainnet block whose BLS aggregate can be checked
;; without touching chain state, into test/filecoin/signer/bls_vectors.cljc.
;;
;; A block header's `BLSAggregate` is one BLS signature over *every* BLS
;; message in the block. Verifying it needs, per message, the sender's public
;; key and the bytes that were signed — and both are reachable from the block
;; alone when the senders are `f3`, because an `f3` address IS the 48-byte
;; public key. (An `f0` sender would need `StateAccountKey` to resolve, i.e.
;; chain state, so blocks containing one are skipped.)
;;
;; That makes this the strongest oracle available for BLS: it exercises the
;; message CID, the address→key extraction, the DST, the G1/G2 placement and
;; the aggregate scheme at once, against a signature a miner actually made.
;;
;;   nbb testdata/gen_bls_vectors.cljs > test/filecoin/signer/bls_vectors.cljc
(ns gen-bls-vectors
  (:require [clojure.string :as str]
            [filecoin.address :as addr]
            [filecoin.rpc :as rpc]))

(def endpoint "https://api.node.glif.io/rpc/v1")
(def want-messages 3)
(def max-blocks 30)

(defn- parse-first [text]
  (js/JSON.parse (first (remove str/blank? (str/split-lines text)))))

(defn- rpc-call [method params]
  (-> (js/fetch endpoint
                #js {:method "POST"
                     :headers #js {"content-type" "application/json"}
                     :body (js/JSON.stringify (clj->js {:jsonrpc "2.0" :method method
                                                        :params params :id 1}))})
      (.then #(.text %))
      (.then (fn [t]
               (let [r (parse-first t)]
                 (if-let [e (aget r "error")]
                   (throw (ex-info (str "rpc: " (js/JSON.stringify e)) {}))
                   (aget r "result")))))))

(defn- emit-message [m]
  (str "{\"Version\" " (aget m "Version")
       " \"To\" " (pr-str (aget m "To"))
       " \"From\" " (pr-str (aget m "From"))
       " \"Nonce\" " (aget m "Nonce")
       " \"Value\" " (pr-str (aget m "Value"))
       " \"GasLimit\" " (aget m "GasLimit")
       " \"GasFeeCap\" " (pr-str (aget m "GasFeeCap"))
       " \"GasPremium\" " (pr-str (aget m "GasPremium"))
       " \"Method\" " (aget m "Method")
       " \"Params\" " (if-let [p (aget m "Params")] (pr-str p) "nil")
       "}"))

(defn- all-f3? [msgs]
  (every? (fn [m] (try (= 3 (addr/protocol (addr/from-string (aget m "From"))))
                       (catch :default _ false)))
          msgs))

(defn- search [cids seen]
  (if (or (empty? cids) (>= seen max-blocks))
    (js/Promise.resolve nil)
    (let [c (first cids)]
      (-> (js/Promise.all #js [(rpc-call "Filecoin.ChainGetBlock" [{"/" c}])
                               (rpc-call "Filecoin.ChainGetBlockMessages" [{"/" c}])])
          (.then (fn [[blk msgs]]
                   (let [bls (array-seq (aget msgs "BlsMessages"))]
                     (if (and (>= (count bls) want-messages) (all-f3? bls))
                       {:cid c :block blk :bls bls}
                       (search (concat (rest cids)
                                       (map #(aget % "/") (array-seq (aget blk "Parents"))))
                               (inc seen))))))))))

(defn -main []
  (-> (rpc-call "Filecoin.ChainHead" [])
      (.then (fn [head] (search (map #(aget % "/") (array-seq (aget head "Cids"))) 0)))
      (.then (fn [found]
               (when-not found
                 (throw (ex-info "no block with enough all-f3 BLS senders found" {})))
               (let [{:keys [cid block bls]} found
                     agg (aget block "BLSAggregate")]
                 (println
                  (str ";; GENERATED by testdata/gen_bls_vectors.cljs — do not edit by hand.\n"
                       ";; A real Filecoin mainnet block. `aggregate` is the one BLS signature\n"
                       ";; its header carries over ALL the messages below; every sender is an\n"
                       ";; f3, so each public key is that address's own payload and no chain\n"
                       ";; state is needed to check it.\n"
                       ";; NOT regenerated in CI: the chain moves, but this is history.\n"
                       "(ns filecoin.signer.bls-vectors)\n\n"
                       "(def block-cid " (pr-str cid) ")\n"
                       "(def height " (aget block "Height") ")\n\n"
                       "(def aggregate\n  {:type " (aget agg "Type")
                       "\n   :data " (pr-str (aget agg "Data")) "})\n\n"
                       "(def bls-messages\n [\n"
                       (str/join "\n" (map #(str "  " (emit-message %)) bls))
                       "\n ])\n")))))
      (.catch (fn [e] (js/console.error (str e)) (js/process.exit 1)))))
(-main)
